#!/usr/bin/expect

spawn ./main -r /home/fuku/DataSet/TPC-H_DATA/region.tbl
expect "Please enter"
send "REGION\n"
expect "How many"
send "3\n"

expect "Please enter"
send "R_REGIONKEY\n"
expect "Please enter number"
send "1\n"
expect "is primary"
send "y\n"
expect "is Compress"
send "n\n"
expect "is Sorted"
send "y\n"
expect "is Index"
send "n\n"

expect "Please enter"
send "R_NAME\n"
expect "Please enter number"
send "5\n"
expect "is primary"
send "n\n"
expect "is Compress"
send "n\n"
expect "is Sorted"
send "n\n"
expect "is Index"
send "n\n"
expect "Please enter fixed"
send "25\n"

expect "Please enter"
send "R_COMMENT\n"
expect "Please enter number"
send "6\n"
expect "is primary"
send "n\n"
expect "is Compress"
send "n\n"
expect "is Sorted"
send "n\n"
expect "is Index"
send "n\n"
expect "Please enter variable"
send "152\n"


set timeout -1
expect eof
